# H2 Console
spring.h2.console.enabled=true
# The path to access the console, default is /h2-console
spring.h2.console.path=/h2-console

# Datasource Properties (to ensure you connect to the same in-memory DB)
spring.datasource.url=jdbc:h2:mem:celonis
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA Properties
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

# Executor Properties
thread.sleep.time=1000